# -*- coding: utf-8 -*-
"""Diccionario de traducción EN→ES de notas olfativas (Top Note).

Cubre ~90% de las ocurrencias de notas del dataset Fragrantica.
Las notas no encontradas se dejan tal cual (en inglés).
"""

NOTE_ES = {
    'musk': 'almizcle', 'white musk': 'almizcle blanco', 'bergamot': 'bergamota',
    'sandalwood': 'sándalo', 'sandalowood': 'sándalo', 'jasmine': 'jazmín',
    'amber': 'ámbar', 'patchouli': 'pachulí', 'vanilla': 'vainilla', 'vanille': 'vainilla',
    'vanila': 'vainilla', 'rose': 'rosa', 'cedar': 'cedro', 'mandarin orange': 'mandarina',
    'vetiver': 'vetiver', 'vetyver': 'vetiver', 'tonka bean': 'haba tonka', 'lemon': 'limón',
    'lavender': 'lavanda', 'orange blossom': 'flor de azahar', 'lily-of-the-valley': 'muguete',
    'pink pepper': 'pimienta rosa', 'cardamom': 'cardamomo', 'violet': 'violeta', 'iris': 'iris',
    'grapefruit': 'pomelo', 'ylang-ylang': 'ylang-ylang', 'leather': 'cuero', 'geranium': 'geranio',
    'oakmoss': 'musgo de roble', 'oak moss': 'musgo de roble', 'peach': 'melocotón',
    'freesia': 'fresia', 'benzoin': 'benjuí', 'cinnamon': 'canela', 'orange': 'naranja',
    'neroli': 'neroli', 'black currant': 'grosella negra', 'peony': 'peonía',
    'nutmeg': 'nuez moscada', 'agarwood (oud)': 'oud (madera de agar)', 'agarwood': 'oud',
    'oud': 'oud', 'ginger': 'jengibre', 'pear': 'pera', 'tuberose': 'nardo', 'incense': 'incienso',
    'saffron': 'azafrán', 'labdanum': 'labdano', 'raspberry': 'frambuesa',
    'woody notes': 'notas amaderadas', 'woodsy notes': 'notas amaderadas', 'magnolia': 'magnolia',
    'heliotrope': 'heliotropo', 'ambergris': 'ámbar gris', 'pepper': 'pimienta', 'gardenia': 'gardenia',
    'apple': 'manzana', 'mint': 'menta', 'coriander': 'cilantro', 'green notes': 'notas verdes',
    'black pepper': 'pimienta negra', 'virginia cedar': 'cedro de virginia', 'citruses': 'cítricos',
    'plum': 'ciruela', 'guaiac wood': 'madera de guayaco', 'guaiacwood': 'madera de guayaco',
    'violet leaf': 'hoja de violeta', 'violet leaves': 'hojas de violeta', 'pineapple': 'piña',
    'carnation': 'clavel', 'sage': 'salvia', 'moss': 'musgo', 'lime': 'lima', 'orchid': 'orquídea',
    'jasmine sambac': 'jazmín sambac', 'lily': 'lirio', 'aldehydes': 'aldehídos', 'basil': 'albahaca',
    'caramel': 'caramelo', 'tobacco': 'tabaco', 'cashmere wood': 'madera de cachemira',
    'tangerine': 'mandarina', 'rosemary': 'romero', 'osmanthus': 'osmanto', 'galbanum': 'gálbano',
    'honey': 'miel', 'orris root': 'raíz de iris', 'petitgrain': 'petitgrain', 'olibanum': 'olíbano',
    'coconut': 'coco', 'clary sage': 'salvia sclarea', 'cloves': 'clavo', 'clove': 'clavo',
    'cypress': 'ciprés', 'cassis': 'cassis', 'amalfi lemon': 'limón de amalfi', 'litchi': 'lichi',
    'ambroxan': 'ambroxan', 'mimosa': 'mimosa', 'cashmeran': 'cashmeran', 'bulgarian rose': 'rosa búlgara',
    'almond': 'almendra', 'artemisia': 'artemisia', 'lotus': 'loto', 'apricot': 'albaricoque',
    'floral notes': 'notas florales', 'cyclamen': 'ciclamen', 'praline': 'praliné', 'spices': 'especias',
    'sea notes': 'notas marinas', 'bitter orange': 'naranja amarga', 'orris': 'iris', 'myrrh': 'mirra',
    'myrhh': 'mirra', 'coffee': 'café', 'red berries': 'frutos rojos',
    'ambrette (musk mallow)': 'ambrette', 'melon': 'melón', 'juniper': 'enebro',
    'honeysuckle': 'madreselva', 'turkish rose': 'rosa turca', 'juniper berries': 'bayas de enebro',
    'water lily': 'nenúfar', 'suede': 'ante', 'tea': 'té', 'african orange flower': 'flor de naranjo africana',
    'narcissus': 'narciso', 'damask rose': 'rosa de damasco', 'green apple': 'manzana verde', 'rum': 'ron',
    'white flowers': 'flores blancas', 'fruity notes': 'notas frutales', 'styrax': 'estoraque',
    'red apple': 'manzana roja', 'frangipani': 'frangipani', 'passionfruit': 'maracuyá',
    'amberwood': 'madera ambarina', 'cypriol oil or nagarmotha': 'cipriol (nagarmotha)', 'elemi': 'elemí',
    'blackberry': 'mora', 'madagascar vanilla': 'vainilla de madagascar', 'lilac': 'lila', 'thyme': 'tomillo',
    'anise': 'anís', 'fig': 'higo', 'birch': 'abedul', 'rhubarb': 'ruibarbo', 'cacao': 'cacao',
    'hyacinth': 'jacinto', 'water notes': 'notas acuáticas', 'watery notes': 'notas acuáticas',
    'yuzu': 'yuzu', 'star anise': 'anís estrellado', 'blood orange': 'naranja sanguina',
    'caraway': 'alcaravea', 'civet': 'civeta', 'haitian vetiver': 'vetiver de haití', 'mango': 'mango',
    'strawberry': 'fresa', 'brazilian rosewood': 'palo de rosa brasileño', 'green leaves': 'hojas verdes',
    'tiare flower': 'flor de tiaré', 'cherry': 'cereza', 'calabrian bergamot': 'bergamota de calabria',
    'green tea': 'té verde', 'spicy notes': 'notas especiadas', 'opoponax': 'opopónaco',
    'palisander rosewood': 'palisandro', 'angelica': 'angélica', 'cumin': 'comino', 'watermelon': 'sandía',
    'licorice': 'regaliz', 'sicilian lemon': 'limón siciliano', 'pomegranate': 'granada', 'milk': 'leche',
    'sugar': 'azúcar', 'castoreum': 'castóreo', 'tolu balsam': 'bálsamo de tolú', 'pink grapefruit': 'pomelo rosa',
    'egyptian jasmine': 'jazmín egipcio', 'bourbon vanilla': 'vainilla bourbon', 'white woods': 'maderas blancas',
    'tarragon': 'estragón', 'may rose': 'rosa de mayo', 'white amber': 'ámbar blanco',
    'peru balsam': 'bálsamo de perú', 'red currant': 'grosella roja', 'powdery notes': 'notas empolvadas',
    'atlas cedar': 'cedro del atlas', 'clementine': 'clementina', 'immortelle': 'siempreviva', 'citron': 'cidra',
    'chamomile': 'manzanilla', 'mate': 'mate', 'papyrus': 'papiro', 'oak': 'roble',
    'french labdanum': 'labdano francés', 'coumarin': 'cumarina', 'fig leaf': 'hoja de higuera',
    'hazelnut': 'avellana', 'lemon verbena': 'hierba luisa', 'bamboo': 'bambú', 'salt': 'sal',
    'nectarine': 'nectarina', 'pomelo': 'pomelo', 'balsam fir': 'abeto balsámico', 'sweet notes': 'notas dulces',
    'cherry blossom': 'flor de cerezo', 'green mandarin': 'mandarina verde', 'sea water': 'agua de mar',
    'red fruits': 'frutos rojos', 'white pepper': 'pimienta blanca', 'ozonic notes': 'notas ozónicas',
    'black tea': 'té negro', 'hibiscus': 'hibisco', 'cassia': 'casia', 'wormwood': 'ajenjo',
    'teak wood': 'madera de teca', 'italian lemon': 'limón italiano', 'davana': 'davana',
    'sichuan pepper': 'pimienta de sichuan', 'dark chocolate': 'chocolate negro', 'chocolate': 'chocolate',
    'sea salt': 'sal marina', 'smoke': 'humo', 'metallic notes': 'notas metálicas',
    'amber xtreme': 'ámbar extremo', 'rose de mai': 'rosa de mayo', 'iso e super': 'iso e super',
}


def translate_note(note: str) -> str:
    n = note.strip().lower()
    return NOTE_ES.get(n, note.strip())
